columns:
  customerID: str
  gender: ['Male', 'Female']
  SeniorCitizen: [0, 1]
  Partner: ['Yes', 'No']
  Dependents: ['Yes', 'No']
  tenure: int
  PhoneService: ['Yes', 'No']
  MultipleLines: ['Yes', 'No', 'No phone service']
  InternetService: ['DSL', 'Fiber optic', 'No']
  OnlineSecurity: ['Yes', 'No', 'No internet service']
  OnlineBackup: ['Yes', 'No', 'No internet service']
  DeviceProtection: ['Yes', 'No', 'No internet service']
  TechSupport: ['Yes', 'No', 'No internet service']
  StreamingTV: ['Yes', 'No', 'No internet service']
  StreamingMovies: ['Yes', 'No', 'No internet service']
  Contract: ['Month-to-month', 'One year', 'Two year']
  PaperlessBilling: ['Yes', 'No']
  PaymentMethod: ['Electronic check', 'Mailed check', 'Bank transfer (automatic)', 'Credit card (automatic)']
  MonthlyCharges: float
  TotalCharges: float
  Churn: ['Yes', 'No']

numerical_columns:
  - tenure
  - MonthlyCharges
  - TotalCharges

categorical_columns:
  gender: ['Male', 'Female']
  SeniorCitizen: [0, 1]
  Partner: ['Yes', 'No']
  Dependents: ['Yes', 'No']
  PhoneService: ['Yes', 'No']
  MultipleLines: ['Yes', 'No', 'No phone service']
  InternetService: ['DSL', 'Fiber optic', 'No']
  OnlineSecurity: ['Yes', 'No', 'No internet service']
  OnlineBackup: ['Yes', 'No', 'No internet service']
  DeviceProtection: ['Yes', 'No', 'No internet service']
  TechSupport: ['Yes', 'No', 'No internet service']
  StreamingTV: ['Yes', 'No', 'No internet service']
  StreamingMovies: ['Yes', 'No', 'No internet service']
  Contract: ['Month-to-month', 'One year', 'Two year']
  PaperlessBilling: ['Yes', 'No']
  PaymentMethod: ['Electronic check', 'Mailed check', 'Bank transfer (automatic)', 'Credit card (automatic)']
  Churn: ['Yes', 'No']
